# LTS snapshot
resolver: lts-16.9

packages:
  - .

extra-deps:
  - rock-0.3.0.0
  - relude-0.7.0.0
  - base-noprelude-4.13.0.0
  - constraints-extras-0.3.0.2
  - dependent-hashmap-0.1.0.1
  - dependent-sum-0.7.1.0
  - dependent-sum-template-0.1.0.3
  - prettyprinter-1.7.0
  - QuickCheck-2.14.1
  - random-1.2.0
  - splitmix-0.1.0.1
